export const FALLBACK_TEMPLATES = {
  chaotic: [
    'Tôi cũng không biết tại sao nó chạy, nhưng đừng chạm vào.',
    'Sửa xong lỗi này lại lòi ra 10 lỗi khác.',
    'Commit này để đây và không nói gì thêm.',
    'Code này viết vào lúc 3h sáng, cẩn thận khi đọc.',
    'Hy vọng là nó hoạt động đúng như mong đợi (chắc thế).',
    'Một thay đổi nhỏ, một thảm họa lớn.',
    'Đã thử mọi cách, và cuối cùng dùng cách tệ nhất.',
    'Xóa code cũ, viết code mới (vẫn lỗi như cũ).',
    'Cầu nguyện cho commit này qua được CI.',
    'Đừng hỏi tại sao, tôi cũng đang tự hỏi mình đây.',
    'Bản vá lỗi thứ n+1 cho cùng một vấn đề.',
    'Thêm một vài dòng code đi mượn từ StackOverflow.',
    'Logic này ảo thật đấy, nhưng nó work.',
    'Comment out đống code này vì nó làm app crash.',
    'Fix bug hay tạo thêm bug? Thời gian sẽ trả lời.',
    'Lần này chắc chắn là lần cuối cùng sửa cái này.',
    'Làm ơn chạy đi, tôi mệt lắm rồi.',
    'Code rác nhưng kết quả là kim cương.',
    'Vừa code vừa khóc.',
    'Lỗi tại server, lỗi tại backend, không phải tại tôi.',
    'Thay đổi một tý cho có vibe.',
    'Sửa cái lỗi mà chỉ UI/UX mới nhận ra.',
    'Commit cho đủ KPI ngày hôm nay.',
    'Debug cả ngày và phát hiện thiếu một dấu chấm phẩy.',
    'Lại là một ngày dài với đống legacy code này.',
    'Thay đổi nhỏ nhưng thay đổi cả cuộc đời dev.',
    'Xóa hết đi làm lại từ đầu có vẻ nhanh hơn.',
    'Commit này chứa đựng tất cả sự thất vọng của tôi.',
    'App chạy rồi, tôi đi ngủ đây.',
    'Đừng đọc code này nếu bạn muốn có một tối yên bình.',
    'Mọi thứ vẫn ổn cho đến khi tôi nhấn Save.',
    'Một sự kết hợp hoàn hảo giữa code và sự may mắn.',
    'Dọn dẹp lại bãi chiến trường sau 1 tuần code.',
    'Commit thần thánh, fix mọi lỗi lầm (hy vọng thế).',
    'Chỉ có Chúa và tôi mới hiểu code này làm gì.',
    'Thêm tính năng mà sếp vừa nảy ra trong lúc đi tắm.',
    'Sửa lỗi "tính năng" mà user báo là bug.',
    'Lại một chiếc commit mang tên hy vọng.',
    'Code này chạy được là nhờ 99% may mắn.',
    'Đã sửa lỗi, nhưng tâm hồn tôi thì chưa.',
    'Làm ơn đừng hỏi tôi logic này là gì.',
    'Xóa 1000 dòng, thêm 10 dòng, lỗi vẫn thế.',
    'Dòng đời xô đẩy, tôi xô đẩy code.',
    'Commit này toát ra vẻ mệt mỏi.',
    'Sửa bug này để chuẩn bị cho bug lớn hơn.',
    'Cứ merge đi, có gì mai mình tính tiếp.',
    'Đã thêm một vài bug mới để dev sau có việc làm.',
    'Logic này vượt xa tầm hiểu biết của nhân loại.',
    'Một bước tiến nhỏ cho repo, một bước lùi cho sức khỏe tôi.',
    'Làm việc nhóm là khi tôi đi sửa lỗi của 10 người khác.',
    'Đã tối ưu hóa code (xóa bớt comment).',
    'Thêm try-catch để che giấu sự bất lực.',
    'Code này là một tác phẩm hội họa, không phải kỹ thuật.',
    'Lỗi không phải do code, lỗi là do nghiệp chướng.',
    'Sửa cái lỗi mà chỉ mình tôi thấy.',
    'Trời xanh mây trắng, code vắng bug xinh (hiếm).',
    'Một commit cực kỳ quan trọng (đổi màu nút).',
    'Đã thêm log để debug lỗi... của năm sau.',
    'Logic này ảo diệu như phim Marvel.',
    'Đừng cố hiểu, hãy cảm nhận nó.',
    'Sửa lỗi chính tả để chứng tỏ mình còn thức.',
    'Lại là một ngày tuyệt vời để phá hỏng production.',
    'Code này là di sản của sự bế tắc.',
    'Xóa code cũ vì nó nhìn ngứa mắt.',
    'Refactor xong thấy lỗi còn nhiều hơn.',
    'Commit này là một lời xin lỗi gửi đến tương lai.',
    'Làm xong rồi, giờ đi tìm việc mới.',
    'Mọi con đường đều dẫn đến bug.',
    'Hack một tý cho nó nhanh.',
    'Đã sửa lỗi, hãy tin tôi.',
    'Một chiếc commit mang đậm tính nhân văn.',
    'Giao diện đã đẹp, code thì vẫn tệ.',
    'Đã thêm tính năng bí mật (không ai biết dùng).',
    'Sửa cái lag mà user thực ra không quan tâm.',
  ],
  passive_aggressive: [
    'Sửa lỗi mà đáng lẽ không nên có nếu đọc kỹ hướng dẫn.',
    'Thêm comment cho những người lười đọc code.',
    'Cập nhật lại cái logic "thông minh" của ai đó.',
    'Refactor lại đống hỗn độn vừa được merge vào.',
    'Vâng, tôi lại phải đi dọn rác cho mọi người đây.',
    'Như đã trao đổi (nhưng không ai thèm nghe).',
    'Cố gắng làm cho code này dễ hiểu nhất có thể cho "bạn".',
    'Sửa lại cái tính năng mà bạn bảo là "xong rồi".',
    'Commit này dành cho người đã phá hỏng repo vào hôm qua.',
    'Thêm log để chứng minh lỗi không phải do tôi.',
    'Ồ, hóa ra code không tự chạy được à?',
    'Lần sau nhớ chạy lint trước khi commit nhé.',
    'Đã sửa lỗi hiển thị mà bạn cam đoan là "không thấy".',
    'Cập nhật tài liệu cho những người thích hỏi hơn là đọc.',
    'Chỉnh lại padding 1px cho vừa lòng sếp.',
    'Nếu bạn đọc được dòng này, có nghĩa là bạn lại merge sai rồi.',
    'Hóa ra logic cơ bản cũng khó đến thế sao?',
    'Lại một commit nữa để sửa lỗi của "ai đó".',
    'Đúng như dự đoán, code của bạn lại crash.',
    'Thêm guard clause vì không tin tưởng input của backend.',
    'Tôi đã cố hết sức để cứu vãn cái dự án này.',
    'Sửa lỗi chính tả trong comment cho nó sang chảnh.',
    'Lại là một ngày đi dọn dẹp hộ người khác.',
    'Nếu code này không chạy, hãy kiểm tra lại trình độ của mình.',
    'Cái này gọi là "tối ưu" à? Thôi để tôi làm lại.',
    'Đã thêm thông báo lỗi cực kỳ rõ ràng, hy vọng bạn đọc được.',
    'Bạn bảo bug này khó lắm, tôi fix trong 5 phút.',
    'Cập nhật lại CSS vì mắt thẩm mỹ của ai đó hơi... lạ.',
    'Xóa bỏ những dòng code vô nghĩa mà bạn mới thêm vào.',
    'Lần sau có copy thì nhớ sửa cả biến nhé.',
    'Tăng độ phức tạp lên cho nó giống project nghìn đô.',
    'Vâng, tôi là người duy nhất quan tâm đến dự án này.',
    'Đã thêm Unit Test cho code của "bạn", đúng là cực hình.',
    'Sửa lại cái typo mà ai đó lười đến không buồn sửa.',
    'Code của bạn chạy mượt mà trên... giấy thôi.',
    'Lại là một màn trình diễn tệ hại của backend.',
    'Tôi đã mất 2 tiếng chỉ để sửa 1 dòng code của bạn.',
    'Cảm ơn vì đã để lại đống legacy này cho tôi.',
    'Thêm loading cho tính năng chậm chạp của bạn.',
    'Lần sau nhớ hỏi ý kiến tôi trước khi code nhé.',
    'Đã sửa lỗi, hy vọng bạn không làm hỏng nó lần nữa.',
    'Một commit để khắc phục hậu quả của cuộc họp hôm qua.',
    'Sửa lại cái logic "hiện đại" mà không ai hiểu.',
    'Cập nhật readme vì dường như bạn không biết đọc code.',
    'Lại là tôi, người hùng thầm lặng dọn rác dự án.',
    'Thêm bớt một vài dòng cho nó ra dáng kỹ sư.',
    'Hóa ra bạn nghĩ null pointer là một tính năng à?',
    'Sửa lỗi crash mà bạn bảo là "không thể xảy ra".',
    'Nếu bạn không biết dùng Git, hãy bảo tôi.',
    'Cập nhật CSS để sửa cái UI thảm họa của bạn.',
    'Đã thêm kiểm tra bảo mật (vì bạn lười).',
    'Lần sau nhớ commit đúng branch nhé thiên tài.',
    'Sửa lại cái API response rác rưởi của backend.',
    'Thêm icon cho người dùng... và cho cả dev lười.',
    'Hóa ra bạn quên chưa save file à?',
    'Lại là công việc dọn dẹp quen thuộc hàng ngày.',
    'Sửa cái bug mà bạn cam đoan là "done 100%".',
    'Đã viết lại hoàn toàn cái component phế vật kia.',
    'Thêm spinner cho trang web chậm như rùa bò này.',
    'Vâng, lỗi lại là do tôi, được chưa?',
    'Sửa lại logic của bạn cho nó giống con người một tý.',
    'Cập nhật script build vì bạn vừa phá nát nó.',
    'Thêm xử lý lỗi vì bạn thích dùng any.',
    'Lỗi to lù lù ra đấy mà bạn vẫn bảo là OK.',
    'Đã fix cái lỗi ngớ ngẩn nhất quả đất.',
    'Sửa bug để cứu vớt danh tiếng công ty.',
    'Lại một lần nữa tôi phải ra tay.',
  ],
  luc_bat: [
    'Code này viết chạy bon bon\nProject hoàn thiện, lòng con nhẹ nhàng.',
    'Sáng nay fix lỗi vừa xong\nChiều nay code chạy, thong dong về nhà.',
    'Lỗi kia nay đã sửa rồi\nCommit một cái, đứng ngồi không yên.',
    'Trăm năm trong cõi người ta\nBug nào rồi cũng phải ra đi thôi.',
    'Đường dài mới biết ngựa hay\nCode dài mới biết lỗi nằm ở đâu.',
    'Thương thay thân phận người dev\nSuốt ngày debug, đêm về nằm mơ.',
    'Trăng lên đầu núi thênh thang\nMerge xong một cái, cả làng đều vui.',
    'Lời chào cao hơn mâm cỗ\nCommit tử tế, repo đẹp ngời.',
    'Học đi đôi với hành thôi\nCode đi đôi với lỗi nồi niêu xoong.',
    'Fix xong một lỗi bất ngờ\nLòng vui sướng quá như vơ được tiền.',
    'Code này không phải dạng vừa\nChạy qua bao lớp, vẫn chưa thấy gì.',
    'Công cha nghĩa mẹ sinh thành\nThầy cô giáo dục, dev dành fix bug.',
    'Anh đi anh nhớ quê nhà\nNhớ canh rau muống, nhớ dòng commit.',
    'Bầu ơi thương lấy bí cùng\nTuy rằng khác module nhưng chung một app.',
    'Lá lành đùm lá rách thôi\nCode mình fix lỗi cho người bên kia.',
    'Sóng gầm sóng cuộn biển Đông\nBug gầm bug rú, nát lòng người dev.',
    'Nhớ ai như nhớ code xưa\nBao lần debug, nắng mưa chẳng nề.',
    'Gần bùn mà chẳng hôi bùn\nGần bug mà vẫn giữ lòng trong veo.',
    'Muốn sang thì bắc cầu kiều\nMuốn app không lỗi thì đừng merge linh tinh.',
    'Lao xao sóng vỗ mạn thuyền\nLao xao commit, muộn phiền tan biến.',
    'Sông sâu còn có kẻ dò\nBug sâu ai biết mà đo cho tường.',
    'Người đi một nửa hồn tôi mất\nCode đi một nửa, lỗi giăng đầy trời.',
    'Chiều chiều ra đứng ngõ sau\nNhìn về repo, ruột đau chín chiều.',
    'Gió đưa cành trúc la đà\nTiếng chuông Slack vang xa khắp phòng.',
    'Cày đêm rồi lại cày ngày\nKhi nào bug hết mới hay thân mình.',
    'Một cây làm chẳng nên non\nBa dev chụm lại, bug còn nhiều hơn.',
    'Cơ hội chỉ đến một lần\nCommit không kỹ, muôn phần khổ đau.',
    'Gừng cay muối mặn xin đừng\nCode sai một ly, đi đời cả team.',
    'Ăn quả nhớ kẻ trồng cây\nMerge code nhớ kẻ ngồi cày đêm đêm.',
    'Có công mài sắt có ngày\nCode chạy mượt mà, sướng thay cuộc đời.',
    'Trống cơm khéo vỗ nên bông\nCode ngoan khéo viết mới không lỗi lầm.',
    'Đồng đăng có phố kỳ lừa\nTrong code có lỗi, lọc lừa user.',
    'Công danh như bóng mây trôi\nFix xong lỗi này, rồi thôi về nhà.',
    'Nhiễu điều phủ lấy giá gương\nPull Request đẹp, mọi đường hanh thông.',
    'Hỡi cô tát nước bên đàng\nSao cô lại để bug hàng đầy kho?',
    'Sáng trăng sáng cả vườn chè\nSáng nay commit, bạn bè ngợi khen.',
    'Thân em như dải lụa đào\nThân dev như dải code vào rồi ra.',
    'Cá không ăn muối cá ươn\nDev không lint code, trăm đường bug vây.',
    'Dù ai đi ngược về xuôi\nNhớ ngày push code, lòng nguôi muộn phiền.',
    'Trèo lên cây bưởi hái hoa\nTrèo lên production, cả nhà hốt hoảng.',
    'Tay bưng chén muối chén gừng\nTay bưng bàn phím, không mừng thì lo.',
    'Hỡi người đi ngược về xuôi\nCode này xịn lắm, xin đừng review.',
    'Mênh mông biển lúa cánh cò\nMênh mông repository, tìm bug đâu ra?',
    'Thầy em là bậc thánh hiền\nCode em là bậc... làm tiền sếp em.',
    'Fix bug cũng giống đi tu\nLòng phải tĩnh lặng, kẻo u u sầu.',
    'Sớm mai thức dậy vui thay\nThấy dòng thông báo: CI xanh rờn.',
    'Học thầy không tày học bạn\nDebug một tiếng bằng ngàn giờ xem.',
  ],
  gen_z: [
    'Fix bug xong thấy mình thật là slay 💅',
    'Vibe hôm nay hơi mệt nhưng code vẫn chạy nhé.',
    'Keo lỳ tái châu với chiếc commit này.',
    'Code này là real, không có miếng giả trân nào luôn.',
    'Et o et, cuối cùng cũng fix xong cái lỗi này!',
    'Xinh đẹp, thông minh và fix bug giỏi.',
    'Ủa alu, sao code cũ lỗi dữ vậy trời?',
    'Hết nước chấm với cái logic này luôn.',
    'Manifest cho chiếc commit này merge phát ăn ngay.',
    'Mãi mận, mãi keo với dự án này.',
    'Sợ hãi các thứ với đống code legacy.',
    'Đã fix xong, quá là chấn động luôn.',
    'Gét gô, đẩy code lên production thôi nào.',
    'Hết cứu với cái lỗi này, nhưng tôi vẫn sửa được.',
    'Mỏ hỗn xíu thôi chứ code ngoan lắm.',
    'Ơ mây dình, gút chóp em luôn.',
    'Lỗi này là do cái nết, không phải do code.',
    'Sửa xong thấy mình quá là flex.',
    'Vô tri xíu nhưng kết quả chất lượng.',
    'Chiếc commit này mang theo sự xinh đẹp của tôi.',
    'Ăn nói xà lơ, code lỗi là do người khác.',
    'Trầm cảm vì bug, nhưng vẫn phải slay.',
    'U là trời, sao nó lại work hay vậy?',
    'Học tập, làm việc và gánh team.',
    'Quá là tuyệt vời, không còn gì để nói.',
    'Vibe hôm nay hơi suy, nhưng code vẫn xanh.',
    'Fix bug là đam mê, tạo bug là định mệnh.',
    'Hết nước chấm cho quả refactor này.',
    'Code này xịn như người viết ra nó vậy.',
    'Đừng nhìn em nữa, nhìn code em đi.',
    'Quá là sến súa luôn cái commit này.',
    'Tới công chuyện luôn với đống bug này.',
    'Xu cà na dính lỗi logic.',
    'Nói chung là mượt, không cần trình bày.',
    'Hết nước chấm, xịn đét đèn lẹt.',
    'Ủa chứ sao, code của tôi mà.',
    'Flex nhẹ nhàng cái tính năng mới.',
    'Mệt muốn xỉu nhưng vẫn phải đẹp.',
    'Nhìn em có giống người vừa fix bug không?',
    'Gì mà căng, code lỗi tý thôi mà.',
    'Chill chill push code rồi đi ngủ.',
    'Ai rồi cũng phải dính bug thôi.',
    'Đã fix, xin đừng hỏi tại sao.',
    'Nết code của em vốn dĩ như thế.',
    'Cảm lạnh với đống code của người cũ.',
    'Slay không lối thoát với logic mới.',
    'Thật là chấn động, thật là hú hồn.',
    'Mắc mệt với mấy cái request vô lý.',
    'Update giao diện cho nó đúng vibe.',
    'Tâm linh mách bảo code này sẽ chạy.',
    'Hỏi thế gian bug là chi?',
    'Mà làm cho dev phải sầu vì bug.',
    'Sửa xong thấy mình thật là chúa tể.',
    'Bá đạo hạt gạo với chiếc commit này.',
    'Không nói nhiều, mượt!',
    'Xịn quá xịn, không gì cản nổi.',
    'Mang theo một rổ sự tự tin lên prod.',
    'Bug này tuổi gì với tôi.',
    'Đã thêm hiệu ứng lung linh lấp lánh.',
    'Gen Z làm việc là phải chất.',
    'Nói cho nghe code này hơi bị đỉnh.',
    'Kệ đời đi, code chạy là được.',
    'Sống ảo trên Facebook, sống thật trên GitHub.',
    'Fix bug giỏi như cách em lãng tránh deadline.',
    'Chiếc commit mang tên sự kiêu sa.',
    'Đã sửa lỗi, mời team check nết.',
    'Style này là riêng tôi một góc trời.',
    'Vô thực luôn cái tính năng này.',
    'Ảo thật đấy, nhưng là thật.',
    'Commit cực suy.',
    'Fix xong lỗi, lòng thanh thản lạ kỳ.',
    'Hết nước chấm, keo lỳ!',
  ],
}
